### ISSUE TITLE
review intro of the book 

### ISSUE THREAD

**Issue by marionlibouban** [tercen/tara_gorsky2016_workflow_guide#11]

**Comment by marionlibouban** [comment]
comments in previous issue #9

**Comment by agouy** [comment]
TO DO:
first feedback
- maybe we should change the naming by using the first author instead of the last author

some comments on intro:

Goals:

- are these questions answered?

Data

- what is each sample?
- what is sPLS? where and how was it computed?

other topics in the intro that should be there:

- what instruments were used to collect the data you used?
- I think we have no statistics analysis in here do we? would it make sense to have one?
- explain what are the operators used and how they work, I should be able to follow the compute steps even if I cannot code them: like we take this and process it like this, we scale that and do this...
- Any PhD students that will present something will be asked how his calculations or representation were made... so All has to be explain 500%
- Visuals: explain how to read and interpret them. How far can one go in interpreting? no fake news
- scientific conclusions if needed

**Comment by agouy** [comment]
@marionlibouban  The latest commit https://github.com/tercen/tara_gorsky2016_workflow_guide/commit/665c15cf7704dd7b681603fefa7ccb42879709dd includes a new version of the introduction. Please have a look.
