### ISSUE TITLE
Make me file: for community

### ISSUE THREAD

**Issue by marionlibouban** [tercen/tara_gorsky2016_workflow_guide#3]

**Comment by marionlibouban** [comment]
@agouy 
-the repository : tara_gorsky2016_workflow,  should be called: tara_gorsky2016_workflow documentation 
-it should include: the readme, the copyme and the makeme

**Comment by agouy** [comment]
@marionlibouban instead of having three separate files like this, shall we structure the documentation as a book with three chapters like:
* 1. introduction (= README)
* 2. how to build the workflow  (= MAKEME)
* 3. how to copy the workflow (= COPYME)

Just like Tercen guides: https://tercen.github.io/starters-guide/
Might be easier for users

**Comment by marionlibouban** [comment]
yes that is a good idea. few notes on the topic

- can you call it: tara_gorsky2016_workflow_guide
-be prepared to have some space for the other part you still have to do (with the map), 2 subpart parts in each chapter?  the book should contain all 
- The intro is a technical one: very quick topic description, data process, instruments, stats, operators, visuals, if available scientific conclusions . 
-We will have on the website and in a readme file in tercen a more high level intro, like the cover of the book you are making.
- For the operator: explain what is a shinny and the concept of how it works, it is not know to the audience

**Comment by agouy** [comment]
thanks, I'm on it

**Comment by agouy** [comment]
@marionlibouban Please have a look at the new version of the guide:
https://tercen.github.io/tara_gorsky2016_workflow_guide/

Let me know your thoughts on the introduction, especially whether it need to be more detailed or not
