### ISSUE TITLE
Review TARA Oceans workflow guide

### ISSUE THREAD

**Issue by agouy** [tercen/tara_gorsky2016_workflow_guide#9]
Please have a look at the new version of the guide:
https://tercen.github.io/tara_gorsky2016_workflow_guide/

It contains three chapters: an introduction ("README"), a tutorial on how to make the workflow ("MAKEME") and hoy to copy it ("COPYME").
Let me know your thoughts on:
* whether the introduction needs to be more detailed or not
* the general structure of the document
* any issue for understanding the workflow making of copying steps

**Comment by marionlibouban** [comment]
@agouy I dont find it very easy to comment /edit the book maybe you have a smart way to show me?

**Comment by marionlibouban** [comment]
@agouy 
first feedback
-maybe we should change the naming by using the first author instead of the last author 

some comments on intro: 

1. Goals:

-are these questions answered?

1. Data

- what is each sample? 
- what is sPLS? where and how was it computed? 

1. other topics in the intro that should be there:

- what **instruments** were used to collect the data you used?
- I think we have no **statistics** analysis in here do we? would it make sense to have one? 
- explain what are the **operators** used and how they work, I should be able to follow the compute steps even if I cannot code them: like we take this and process it like this, we scale that and do this...
Any PhD students that will present something will be asked how his calculations or representation were made... so All has to be explain 500% 
- **Visuals**: explain how to read and interpret them.  How far can one go in interpreting? no fake news
-  **scientific conclusions** if needed

**Comment by marionlibouban** [comment]
@agouy @fnaji @amaurel 
For the tutorial part where we should show how to copy the workflow, AlexG should be working from the project/workflow final location. So, I created an issue for AlexM to create a tercen project under Explore.  AlexG you have to wait for it to be done to continue on the tutorials because all your screen shots will be wrong. 
When AlexG when you have the two parts, how to copy and how to make, for the two workflow parts, I will review the parts of the book. For now we focus on fixing the intro, first feedback in previous comments,

**Comment by agouy** [comment]
> @agouy I dont find it very easy to comment /edit the book maybe you have a smart way to show me?

@marionlibouban I don't see how we could make it easier to review web documents. If you need to refer to some specific places of the document, maybe you could look at the source of the document with line numbers? For example chapter 2:
https://github.com/tercen/tara_gorsky2016_workflow_guide/blob/master/02-make-tara-workflow.Rmd

It's just a suggestion, to me the feedback as you gave it  was clear enough.

**Comment by marionlibouban** [comment]
@agouy can you point to the new intro version?

**Comment by agouy** [comment]
@marionlibouban it's here:
https://tercen.github.io/tara_guidi2016_workflow_guide/

source is here:
https://github.com/tercen/tara_guidi2016_workflow_guide/blob/master/index.Rmd

**Comment by agouy** [comment]
@marionlibouban latest version is ready
https://tercen.github.io/tara_guidi2016_workflow_guide/
